import type { ShoppingCategory } from "./types";

const KEYWORD_MAP: Record<string, ShoppingCategory> = {
  milk: "dairy",
  cheese: "dairy",
  yogurt: "dairy",
  butter: "dairy",
  cream: "dairy",
  eggs: "dairy",
  egg: "dairy",
  chicken: "meat",
  beef: "meat",
  pork: "meat",
  bacon: "meat",
  turkey: "meat",
  sausage: "meat",
  fish: "meat",
  salmon: "meat",
  shrimp: "meat",
  apple: "produce",
  apples: "produce",
  banana: "produce",
  bananas: "produce",
  lettuce: "produce",
  spinach: "produce",
  tomato: "produce",
  tomatoes: "produce",
  onion: "produce",
  onions: "produce",
  potato: "produce",
  potatoes: "produce",
  garlic: "produce",
  carrot: "produce",
  carrots: "produce",
  pepper: "produce",
  cucumber: "produce",
  broccoli: "produce",
  avocado: "produce",
  berries: "produce",
  grapes: "produce",
  icecream: "frozen",
  "ice cream": "frozen",
  frozen: "frozen",
  pizza: "frozen",
  bread: "pantry",
  rice: "pantry",
  pasta: "pantry",
  cereal: "pantry",
  flour: "pantry",
  sugar: "pantry",
  oil: "pantry",
  sauce: "pantry",
  beans: "pantry",
  soup: "pantry",
  coffee: "pantry",
  tea: "pantry",
  protein: "pantry",
  "protein powder": "pantry",
  soap: "household",
  "dish soap": "household",
  detergent: "household",
  "toilet paper": "household",
  "paper towel": "household",
  "paper towels": "household",
  napkins: "household",
  trash: "household",
  "trash bags": "household",
  shampoo: "pharmacy",
  toothpaste: "pharmacy",
  vitamins: "pharmacy",
  medicine: "pharmacy",
  ibuprofen: "pharmacy",
  bandages: "pharmacy",
  slacks: "clothes",
  pants: "clothes",
  jeans: "clothes",
  shirt: "clothes",
  tshirt: "clothes",
  "t-shirt": "clothes",
  blouse: "clothes",
  sweater: "clothes",
  hoodie: "clothes",
  jacket: "clothes",
  coat: "clothes",
  socks: "clothes",
  shoes: "clothes",
  sneakers: "clothes",
  boots: "clothes",
  underwear: "clothes",
  dress: "clothes",
  skirt: "clothes",
  shorts: "clothes",
  belt: "clothes",
  gloves: "clothes",
  scarf: "clothes",
};

export function guessCategory(name: string): ShoppingCategory {
  const key = name.trim().toLowerCase();
  if (KEYWORD_MAP[key]) return KEYWORD_MAP[key];

  for (const [word, category] of Object.entries(KEYWORD_MAP)) {
    if (key.includes(word)) return category;
  }

  return "other";
}
